# Dados de conexão
spring.datasource.url=jdbc:postgresql://localhost:5432/focustask_db
spring.datasource.username=admin
spring.datasource.password=adminpassword

# O Hibernate (JPA) lê suas classes e cria as tabelas sozinho
spring.jpa.hibernate.ddl-auto=update

# Para você ver o SQL "raiz" no console enquanto estuda
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
